# PostgreSQL. Versions 9.1 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: sewagodimo
  port: 5432

development:
  <<: *default
  database: moshal_development


test:
  <<: *default
  database: moshal_test


production:
  <<: *default
  database: moshal_production
  username: moshal
  password: <%= ENV['MOSHAL_DATABASE_PASSWORD'] %>
